name: ustriage
version: master
summary: Output Ubuntu Server Launchpad bugs for triage
description: |
  Connect to Launchpad and collect Ubuntu Server bugs for triage.
  List can be set to a specific or range of dates and allows for
  filtering based on various options.

grade: stable
confinement: classic

apps:
    ustriage:
        command: ustriage/ustriage.py

parts:
    ustriage:
        plugin: dump
        source: https://github.com/powersj/ubuntu-server-triage
        source-type: git
        stage-packages:
            - python3-launchpadlib
